### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by liamlangli** [enkimute/webgl2_pathtrace#1]
l = minc(scaler * mix(b + 1.0 - txc, -b - txc, vec3(lessThan(dir, vec3(0.0))))) + EPSILON * 50.0;

what does this line of code means

**Comment by enkimute** [comment]
Hi AngusLang,

To accelerate finding the polygons of interest, the demo uses a distance-field-grid-accelerator (yes I just made that name up). It works pretty much like a normal grid accelerator, except that empty gridcells are filled with the signed distance to the closest non-empty cell. This allows the trace function to quickly jump over large empty areas in the grid. That particular line calculates the offset to the next cell border (the algorithm I use is a modified GPU friendly DDA. it selects the minimum step and direction needed to reach the next closest non-empty gridcell boundary.)

The EPSILON is me trying to hack around precision differences between several different webGL2 implementations. The minc selects the smallest component (i.e. nearest boundary), the mix picks the next boundary 'up' (or left or towards), or the opposite one depending on the direction (lessThan) of the current ray.  

Hope that helps - if you read up on DDA, the similarities and changes I made should become obvious.
(and feel free to ask for more info).

cheers.
